app:
  name: spring_boot_authentication
  MOUNT_PATH: src/main/resources/storage
server:
  port: 8888
spring:
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  datasource:
    url: jdbc:mysql://localhost:3300/spring_db?useSSL=false
    username: admin
    password: 1234
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0
    driverClassName: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        # dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update # when start u need to create table u can change the value as an create or update 
    hibernate:
      ddl-auto: create
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
  sql:
    init:
      continue-on-error: true
  web:
    resources:
      resource-locations: "classpath:/storage/"
      static-locations: file:src/main/resources/static/,file:src/main/storage/
      cache:
        period: 0

        #  data:

        #    mongodb:

        #      uri: mongodb://spring_user:1234@localhost:27018/spring_db

        #      database: spring_db

        #    autoconfigure:

        #      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  # web:
  #   resources:
  #     static-locations: file:/src/main/resources/static/
  #     cache:
  #       period: 0

        # web:

        #    resources:

        #       static-locations: classpath:/storage/,classpath:/categories/
logging:
  file: 
    name: src/main/resources/storage/logger/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    org:
      springframework:
        web: ERROR
      hibernate: 
        SQL: DEBUG
        type:
          descriptor:
            sql:
             BasicBinder: TRACE
    com:
      howtodoinjava: INFO
      demo:
        aop: INFO
    
bezkoder:
  app:
    jwtSecret: +VvMvH8Y+/QYlYPHdkXwnO8wkVWpbld94zPohs1goMnFoEqdOGiDjMVBDg9i+wFNi/0de0JfOY0YTw+BfOZm+g==
    jwtExpirationMs: 3600000