app:
  name: spring_boot_authentication
  MOUNT_PATH: src/main/resources/storage
server:
  port: 8888
spring:
#  data:
#    mongodb:
#      uri: mongodb://spring_user:1234@localhost:27018/spring_db
#      database: spring_db
#    autoconfigure:
#      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:mysql://localhost:3300/spring_db?useSSL=false
    username: admin
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
logging:
  file: 
    name: src/main/resources/storage/logger/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
    com:
      howtodoinjava: INFO
      demo:
        aop: INFO
    
bezkoder:
  app:
    jwtSecret: +VvMvH8Y+/QYlYPHdkXwnO8wkVWpbld94zPohs1goMnFoEqdOGiDjMVBDg9i+wFNi/0de0JfOY0YTw+BfOZm+g==
    jwtExpirationMs: 3600000