version: "3.8"
services:
#  database:
#    mem_limit: 128m
#    mem_reservation: 128M
#    cpus: 0.3
#    image: mongo:5.0.5
#    ports:
#      - 27018:27017
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=123456
#      - MONGO_INITDB_DATABASE=spring_db
#      - MONGO_INITDB_USERNAME=spring_user
#      - MONGO_INITDB_PASSWORD=1234
#    volumes:
#      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
#      - ./db:/data/db

  mysql:
    mem_limit: 200M
    mem_reservation: 200M
    cpus: 0.3
    image: mysql:8.0
    restart: always
    ports:
      - 3300:3306
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=admin
      - MYSQL_DATABASE=spring_db
      - MYSQL_PASSWORD=1234
    volumes:
      - ./mysql:/var/lib/mysql
  # mysql-schema:
  #   mem_limit: 516M
  #   mem_reservation: 516M
  #   # cpus: 0.3
  #   image: mysql:8.0
  #   ports:
  #     - 3301:3306
  #   environment:
  #     - MYSQL_ROOT_USER=root
  #     - MYSQL_ROOT_PASSWORD=123456
  #     - MYSQL_USER=admin
  #     - MYSQL_DATABASE=spring_db
  #     - MYSQL_PASSWORD=1234
  #   volumes:
  #     - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
  #     - ./mysql-ecommerce:/var/lib/mysql